# Generated by Django 6.0.5 on 2026-05-12 08:09

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('full_name', models.CharField(max_length=150, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='نام شرکت')),
                ('power_required', models.CharField(blank=True, max_length=100, verbose_name='توان مورد نیاز')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('is_replied', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='content_ar',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='المحتوى (عربی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='محتوا (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_fa',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='محتوا (فارسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент (روسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_ar',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='وصف ميتا (عربی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Meta Description (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_fa',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='توضیحات متا (فارسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Мета-описание (روسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_ar',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان سئو (عربی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='SEO Title (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_fa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='عنوان سئو (فارسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='SEO Title (روسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ar',
            field=models.CharField(blank=True, max_length=250, verbose_name='العنوان (عربی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fa',
            field=models.CharField(default='', max_length=250, verbose_name='عنوان مقاله (فارسی)'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название (روسی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='الوصف (عربی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Description (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_fa',
            field=models.TextField(default='', verbose_name='توضیحات (فارسی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Описание (روسی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='منتشر شده'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_ar',
            field=models.CharField(blank=True, max_length=100, verbose_name='الموقع (عربی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Location (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_fa',
            field=models.CharField(default='', max_length=100, verbose_name='محل اجرا (فارسی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='location_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='Местоположение (روسی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, verbose_name='العنوان (عربی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_fa',
            field=models.CharField(default='', max_length=200, verbose_name='عنوان (فارسی)'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название (روسی)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_summary',
            field=models.TextField(blank=True, verbose_name='خلاصه درباره ما (قدیمی - از متون ثابت استفاده کنید)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_text',
            field=models.CharField(blank=True, max_length=50, verbose_name='متن دکمه فراخوان CTA (قدیمی - از متون ثابت استفاده کنید)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.TextField(blank=True, verbose_name='متن زیر تیتر صفحه اصلی (قدیمی - از متون ثابت استفاده کنید)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='تیتر بزرگ صفحه اصلی (قدیمی - از متون ثابت استفاده کنید)'),
        ),
    ]
